### ISSUE TITLE
Firmware G973FXXUFHVG4

### ISSUE THREAD

**Issue by Gangobringo** [Linux4/firmware-update#3]
Hello there,
I wanted to install the firmware G973FXXUFHVG4. My problem is, this is a binary ver 15 and I allready have Firmware with ver 16 installed. I cant downgrade.
Is there a newer firmware update in planning? 
Regards

**Comment by Linux4** [comment]
https://github.com/Linux4/firmware-update/commit/6b2640bd389f60cfe1dba84878a06be8c563a70b

Updating firmware yourself is no longer recommended tho, especially since T based ROMs now ship known to be working firmware with the ROM.
